package cbcb.kmulus.allpairs.comparison;

/** Groups a set of items such that:
 * <ul>
 * 	<li>any two items are found within the same group exactly once</li>
 * 	<li>across all groups, all pairs of items can be found within the same group</li>
 * </ul>
 */
public interface ExhaustiveUniqueGrouper {

	/** Returns the identifiers for the group to which this item belongs. */
	public long[] getGroups(long id);
	
	/** Returns the number of items which have been mapped to groups by this grouper. */
	public long getNumItems();
	
	/** Returns the number of groups which have been generated by this grouper. */
	public long getNumGroups();
}
